/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.12 ./src/Models/2d_house.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/2d_house.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-1.33, 7.72, -0.56]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[14.61, 0.67, 14.61]}>
        <mesh geometry={nodes['front-door-02_1'].geometry} material={materials['front-door-02']} />
        <mesh geometry={nodes['front-door-02_2'].geometry} material={materials.glass} />
        <mesh geometry={nodes['front-door-02_3'].geometry} material={materials['Material.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/2d_house.glb')
